set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports rx_data]
set_property IOSTANDARD LVCMOS33 [get_ports tx_data]
set_property PACKAGE_PIN E3 [get_ports clk_in]
set_property PACKAGE_PIN C17 [get_ports rx_data]
set_property PACKAGE_PIN D18 [get_ports tx_data]

set_property DRIVE 12 [get_ports tx_data]
set_property SLEW SLOW [get_ports tx_data]

set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property PACKAGE_PIN H17 [get_ports {data[0]}]
set_property PACKAGE_PIN K15 [get_ports {data[1]}]
set_property PACKAGE_PIN J13 [get_ports {data[2]}]
set_property PACKAGE_PIN N14 [get_ports {data[3]}]
set_property PACKAGE_PIN R18 [get_ports {data[4]}]
set_property PACKAGE_PIN V17 [get_ports {data[5]}]
set_property PACKAGE_PIN U17 [get_ports {data[6]}]
set_property PACKAGE_PIN U16 [get_ports {data[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports data_rdy]
set_property PACKAGE_PIN V11 [get_ports data_rdy]

set_property PACKAGE_PIN P17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {send_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {send_data[0]}]
set_property PACKAGE_PIN V10 [get_ports {send_data[7]}]
set_property PACKAGE_PIN U11 [get_ports {send_data[6]}]
set_property PACKAGE_PIN U12 [get_ports {send_data[5]}]
set_property PACKAGE_PIN H6 [get_ports {send_data[4]}]
set_property PACKAGE_PIN T13 [get_ports {send_data[3]}]
set_property PACKAGE_PIN R16 [get_ports {send_data[2]}]
set_property PACKAGE_PIN U8 [get_ports {send_data[1]}]
set_property PACKAGE_PIN T8 [get_ports {send_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports send]
set_property PACKAGE_PIN P18 [get_ports send]
set_property PACKAGE_PIN V12 [get_ports send_rdy]
set_property IOSTANDARD LVCMOS33 [get_ports send_rdy]
